steps:
  # Install dependencies for UI
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["ci"]
    dir: "ui"
  # Build UI
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "build"]
    dir: "ui"
  # Run unit tests and e2e tests
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "test:ci"]
    dir: "ui"
  # Deploy to Firebase
  - name: gcr.io/cards-against-containers/firebase
    args: ["deploy"]
    dir: "ui"
