steps:
  # Install dependencies for UI
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["ci"]
    dir: "ui"
  # Build UI
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "build"]
    dir: "ui"
  # Run unitests
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "test:unit"]
    dir: "ui"
  # Run e2e tests (electron)
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "test:e2e:ci:electron"]
    dir: "ui"
    env: ["CYPRESS_BASE_URL=http://localhost:5000"]
  # Run e2e tests (chrome)
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "test:e2e:ci:chrome"]
    dir: "ui"
    env: ["CYPRESS_BASE_URL=http://localhost:5000"]
  # Run e2e tests (firefox)
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "test:e2e:ci:firefox"]
    dir: "ui"
    env: ["CYPRESS_BASE_URL=http://localhost:5000"]
  # Run Percy visual tests
  - name: cypress/browsers:node12.18.3-chrome87-ff82
    entrypoint: "npm"
    args: ["run", "test:e2e:ci:percy"]
    dir: "ui"
    env: ["CYPRESS_BASE_URL=http://localhost:5000"]
  # Deploy to Firebase
  - name: gcr.io/cards-against-containers/firebase
    args: ["deploy"]
    dir: "ui"
