name: UI

on:
  push:
    paths:
      - ".github/workflows/ui.yaml"
      - "ui/**"
      - "!**/*.md"

defaults:
  run:
    working-directory: ./ui

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build production code
        run: npm run build

      - name: Upload build files 
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: |
            ./ui/**
            !./ui/node_modules/**

  unit-tests:
    name: Run React component unit tests
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Fetch build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: repo
          path: ./ui
      - run: npm ci
      - run: npm run test:unit

  e2e-tests:
    name: Run end-to-end tests
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        browser: [chrome, firefox, electron]
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Fetch build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: repo
          path: ./ui
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:ci
          wait-on: http://localhost:5000
          browser: ${{ matrix.browser }}
          headless: true
          working-directory: ./ui
          config: baseUrl=http://localhost:5000
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}