name: Cards Against Container CI (UI only)

on: 
  push:
    paths-ignore:
    - 'rest-api/**'
    - '**/*.md'
  pull_request:
    paths-ignore:
    - 'rest-api/**'
    - '**/*.md'

defaults:
  run:
    working-directory: ./ui

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ui/package-lock.json') }}
        restore-keys:
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-      
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm run test:unit
    - name: Build production code and start server
      uses: cypress-io/github-action@v2
      with:
        start: npm run start:ci
        wait-on: 'http://localhost:5000'
        browser: chrome
        headless: true
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}